In [25]:
import pandas as pd
import numpy as np
import glob

In [26]:
files = glob.glob('../data/raw/*.csv')

df_list = []

for file in files:
    temp_df = pd.read_csv(file)
    df_list.append(temp_df)

df = pd.concat(df_list, ignore_index= True)

print("Dataset shape", df.shape)

Dataset shape (18622, 8)

In [27]:
df.head

<bound method NDFrame.head of         Location        time  precipitation_sum  temperature_2m_mean  \
0            Hue  2001-01-01                2.6                 20.2
1            Hue  2001-01-02                0.0                 21.1
2            Hue  2001-01-03                1.0                 21.6
3            Hue  2001-01-04                6.7                 21.2
4            Hue  2001-01-05                4.8                 22.1
...          ...         ...                ...                  ...
18617  Quang Nam  2026-06-25                0.3                 33.6
18618  Quang Nam  2026-06-26                7.2                 32.0
18619  Quang Nam  2026-06-27                3.7                 31.3
18620  Quang Nam  2026-06-28                7.0                 31.1
18621  Quang Nam  2026-06-29               14.3                 29.9

       relative_humidity_2m_mean  surface_pressure_mean  wind_speed_10m_max  \
0                             82                 1013.3                 9.6
1                             82                 1011.8                14.1
2                             85                 1012.9                12.7
3                             91                 1014.2                15.5
4                             90                 1014.0                14.5
...                          ...                    ...                 ...
18617                         55                 1003.1                19.8
18618                         64                 1003.9                18.7
18619                         68                 1004.1                 7.1
18620                         68                 1003.9                12.9
18621                         78                 1003.9                19.6

       river_discharge
0                 1.56
1                 1.09
2                 0.75
3                 0.72
4                 0.92
...                ...
18617             6.24
18618             6.19
18619             6.35
18620             6.43
18621             6.55

[18622 rows x 8 columns]>

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18622 entries, 0 to 18621
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Location                   18622 non-null  object
 1   time                       18622 non-null  object
 2   precipitation_sum          18622 non-null  float64
 3   temperature_2m_mean        18622 non-null  float64
 4   relative_humidity_2m_mean  18622 non-null  int64
 5   surface_pressure_mean      18622 non-null  float64
 6   wind_speed_10m_max         18622 non-null  float64
 7   river_discharge            18622 non-null  float64
dtypes: float64(5), int64(1), object(2)
memory usage: 1.1+ MB

In [29]:
df.describe()

,precipitation_sum,temperature_2m_mean,relative_humidity_2m_mean,surface_pressure_mean,wind_speed_10m_max,river_discharge
count,18622.000000,18622.000000,18622.000000,18622.000000,18622.000000,18622.000000
mean,7.840307,25.742439,83.083879,1009.344190,14.313602,23.388731
std,16.772924,3.278230,7.024499,5.187067,4.598161,68.224639
min,0.000000,14.100000,45.000000,984.400000,4.200000,0.080000
25%,0.200000,23.300000,80.000000,1005.300000,11.200000,0.670000
50%,2.100000,26.000000,84.000000,1009.000000,13.600000,6.530000
75%,8.400000,28.400000,88.000000,1013.300000,16.600000,14.890000
max,398.800000,34.600000,97.000000,1028.400000,64.600000,1569.360000

In [30]:
df = df.rename(columns = {
    "Location": "location",
    "time": "date",
    "precipitation_sum": "rainfall",
    "temperature_2m_mean": "temperature",
    "relative_humidity_2m_mean": "humidity",
    "surface_pressure_mean": "pressure",
    "wind_speed_10m_max": "wind_speed"
})

In [31]:
df["date"] = pd.to_datetime(df["date"])
df['humidity'] = df['humidity'].astype('float64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18622 entries, 0 to 18621
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   location         18622 non-null  object
 1   date             18622 non-null  datetime64[ns]
 2   rainfall         18622 non-null  float64
 3   temperature      18622 non-null  float64
 4   humidity         18622 non-null  float64
 5   pressure         18622 non-null  float64
 6   wind_speed       18622 non-null  float64
 7   river_discharge  18622 non-null  float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 1.1+ MB

In [32]:
df.head()

,location,date,rainfall,temperature,humidity,pressure,wind_speed,river_discharge
0,Hue,2001-01-01,2.6,20.2,82.0,1013.3,9.6,1.56
1,Hue,2001-01-02,0.0,21.1,82.0,1011.8,14.1,1.09
2,Hue,2001-01-03,1.0,21.6,85.0,1012.9,12.7,0.75
3,Hue,2001-01-04,6.7,21.2,91.0,1014.2,15.5,0.72
4,Hue,2001-01-05,4.8,22.1,90.0,1014.0,14.5,0.92

In [33]:
cols = ["date","location"]
other_cols = [c for c in df.columns if c not in cols]
df = df[cols + other_cols]
df.head()

,date,location,rainfall,temperature,humidity,pressure,wind_speed,river_discharge
0,2001-01-01,Hue,2.6,20.2,82.0,1013.3,9.6,1.56
1,2001-01-02,Hue,0.0,21.1,82.0,1011.8,14.1,1.09
2,2001-01-03,Hue,1.0,21.6,85.0,1012.9,12.7,0.75
3,2001-01-04,Hue,6.7,21.2,91.0,1014.2,15.5,0.72
4,2001-01-05,Hue,4.8,22.1,90.0,1014.0,14.5,0.92

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18622 entries, 0 to 18621
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             18622 non-null  datetime64[ns]
 1   location         18622 non-null  object
 2   rainfall         18622 non-null  float64
 3   temperature      18622 non-null  float64
 4   humidity         18622 non-null  float64
 5   pressure         18622 non-null  float64
 6   wind_speed       18622 non-null  float64
 7   river_discharge  18622 non-null  float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 1.1+ MB

In [36]:
df.describe()

,date,rainfall,temperature,humidity,pressure,wind_speed,river_discharge
count,18622,18622.000000,18622.000000,18622.000000,18622.000000,18622.000000,18622.000000
mean,2013-09-30 00:00:00,7.840307,25.742439,83.083879,1009.344190,14.313602,23.388731
min,2001-01-01 00:00:00,0.000000,14.100000,45.000000,984.400000,4.200000,0.080000
25%,2007-05-17 06:00:00,0.200000,23.300000,80.000000,1005.300000,11.200000,0.670000
50%,2013-09-30 00:00:00,2.100000,26.000000,84.000000,1009.000000,13.600000,6.530000
75%,2020-02-13 18:00:00,8.400000,28.400000,88.000000,1013.300000,16.600000,14.890000
max,2026-06-29 00:00:00,398.800000,34.600000,97.000000,1028.400000,64.600000,1569.360000
std,NaN,16.772924,3.278230,7.024499,5.187067,4.598161,68.224639

In [37]:
import os

In [38]:
output_path = '../data/cleaned/cleaned_weather.csv'

# Export CSV
df.to_csv(output_path, index=False)

print('Done')

Done