In [1]:
import pandas as pd
import numpy as np
import glob

In [2]:
files = glob.glob('../data/raw/*.csv')

df_list = []

for file in files:
    temp_df = pd.read_csv(file)
    df_list.append(temp_df)

df = pd.concat(df_list, ignore_index= True)

print("Dataset shape", df.shape)

Dataset shape (18286, 8)

In [3]:
df.head

<bound method NDFrame.head of         Location        time  precipitation_sum  temperature_2m_mean  \
0            Hue  2001-07-01                0.0                 28.6
1            Hue  2001-07-02                0.2                 29.1
2            Hue  2001-07-03                1.8                 28.6
3            Hue  2001-07-04               13.8                 27.8
4            Hue  2001-07-05                0.0                 28.8
...          ...         ...                ...                  ...
18281  Quang Nam  2026-07-08                1.8                 30.5
18282  Quang Nam  2026-07-09                3.3                 31.0
18283  Quang Nam  2026-07-10               11.1                 28.7
18284  Quang Nam  2026-07-11                1.2                 31.4
18285  Quang Nam  2026-07-12                7.4                 31.1

       relative_humidity_2m_mean  surface_pressure_mean  wind_speed_10m_max  \
0                             68                 1000.4                24.8
1                             70                  998.7                20.9
2                             79                  999.6                 6.9
3                             85                  999.9                11.5
4                             74                  997.5                25.2
...                          ...                    ...                 ...
18281                         66                 1003.7                20.4
18282                         64                 1003.6                24.0
18283                         80                 1002.9                14.9
18284                         58                 1000.0                24.6
18285                         63                 1000.0                16.6

       river_discharge
0                 0.53
1                 0.44
2                 0.42
3                 0.44
4                 0.41
...                ...
18281             9.02
18282             9.84
18283             7.73
18284             7.69
18285             7.71

[18286 rows x 8 columns]>

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18286 entries, 0 to 18285
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Location                   18286 non-null  object
 1   time                       18286 non-null  object
 2   precipitation_sum          18286 non-null  float64
 3   temperature_2m_mean        18286 non-null  float64
 4   relative_humidity_2m_mean  18286 non-null  int64
 5   surface_pressure_mean      18286 non-null  float64
 6   wind_speed_10m_max         18286 non-null  float64
 7   river_discharge            18286 non-null  float64
dtypes: float64(5), int64(1), object(2)
memory usage: 1.1+ MB

In [5]:
df.describe()

,precipitation_sum,temperature_2m_mean,relative_humidity_2m_mean,surface_pressure_mean,wind_speed_10m_max,river_discharge
count,18286.000000,18286.000000,18286.000000,18286.000000,18286.00000,18286.000000
mean,7.876736,25.758537,83.012851,1009.344411,14.33938,23.587589
std,16.872527,3.285306,7.064243,5.201703,4.61339,68.787972
min,0.000000,14.100000,45.000000,984.400000,4.20000,0.080000
25%,0.200000,23.300000,80.000000,1005.300000,11.30000,0.670000
50%,2.200000,26.000000,84.000000,1009.000000,13.60000,6.530000
75%,8.400000,28.400000,88.000000,1013.300000,16.60000,14.850000
max,398.800000,34.600000,97.000000,1028.400000,64.60000,1569.360000

In [6]:
df = df.rename(columns = {
    "Location": "location",
    "time": "date",
    "precipitation_sum": "rainfall",
    "temperature_2m_mean": "temperature",
    "relative_humidity_2m_mean": "humidity",
    "surface_pressure_mean": "pressure",
    "wind_speed_10m_max": "wind_speed"
})

In [7]:
df["date"] = pd.to_datetime(df["date"])
df['humidity'] = df['humidity'].astype('float64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18286 entries, 0 to 18285
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   location         18286 non-null  object
 1   date             18286 non-null  datetime64[ns]
 2   rainfall         18286 non-null  float64
 3   temperature      18286 non-null  float64
 4   humidity         18286 non-null  float64
 5   pressure         18286 non-null  float64
 6   wind_speed       18286 non-null  float64
 7   river_discharge  18286 non-null  float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 1.1+ MB

In [8]:
df.head()

,location,date,rainfall,temperature,humidity,pressure,wind_speed,river_discharge
0,Hue,2001-07-01,0.0,28.6,68.0,1000.4,24.8,0.53
1,Hue,2001-07-02,0.2,29.1,70.0,998.7,20.9,0.44
2,Hue,2001-07-03,1.8,28.6,79.0,999.6,6.9,0.42
3,Hue,2001-07-04,13.8,27.8,85.0,999.9,11.5,0.44
4,Hue,2001-07-05,0.0,28.8,74.0,997.5,25.2,0.41

In [9]:
cols = ["date","location"]
other_cols = [c for c in df.columns if c not in cols]
df = df[cols + other_cols]
df.head()

,date,location,rainfall,temperature,humidity,pressure,wind_speed,river_discharge
0,2001-07-01,Hue,0.0,28.6,68.0,1000.4,24.8,0.53
1,2001-07-02,Hue,0.2,29.1,70.0,998.7,20.9,0.44
2,2001-07-03,Hue,1.8,28.6,79.0,999.6,6.9,0.42
3,2001-07-04,Hue,13.8,27.8,85.0,999.9,11.5,0.44
4,2001-07-05,Hue,0.0,28.8,74.0,997.5,25.2,0.41

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18286 entries, 0 to 18285
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             18286 non-null  datetime64[ns]
 1   location         18286 non-null  object
 2   rainfall         18286 non-null  float64
 3   temperature      18286 non-null  float64
 4   humidity         18286 non-null  float64
 5   pressure         18286 non-null  float64
 6   wind_speed       18286 non-null  float64
 7   river_discharge  18286 non-null  float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 1.1+ MB

In [12]:
df.describe()

,date,rainfall,temperature,humidity,pressure,wind_speed,river_discharge
count,18286,18286.000000,18286.000000,18286.000000,18286.000000,18286.00000,18286.000000
mean,2014-01-05 00:00:00,7.876736,25.758537,83.012851,1009.344411,14.33938,23.587589
min,2001-07-01 00:00:00,0.000000,14.100000,45.000000,984.400000,4.20000,0.080000
25%,2007-10-03 06:00:00,0.200000,23.300000,80.000000,1005.300000,11.30000,0.670000
50%,2014-01-05 00:00:00,2.200000,26.000000,84.000000,1009.000000,13.60000,6.530000
75%,2020-04-08 18:00:00,8.400000,28.400000,88.000000,1013.300000,16.60000,14.850000
max,2026-07-12 00:00:00,398.800000,34.600000,97.000000,1028.400000,64.60000,1569.360000
std,NaN,16.872527,3.285306,7.064243,5.201703,4.61339,68.787972

In [13]:
import os

In [ ]:
output_path = '../data/cleaned/weather_cleaned.csv'

# Export CSV
df.to_csv(output_path, index=False)

print('Done')

Done