In [9]:
import pandas as pd
import numpy as np
import glob

In [10]:
files = glob.glob('../data/data_raw/*.csv')

df_list = []

for file in files:
    temp_df = pd.read_csv(file)
    df_list.append(temp_df)

df = pd.concat(df_list, ignore_index= True)

print("Dataset shape", df.shape)

Dataset shape (18306, 8)

In [11]:
df.head

<bound method NDFrame.head of         Location        time  precipitation_sum  temperature_2m_mean  \
0            Hue  2001-07-01                0.0                 28.6
1            Hue  2001-07-02                0.2                 29.1
2            Hue  2001-07-03                1.8                 28.6
3            Hue  2001-07-04               13.8                 27.8
4            Hue  2001-07-05                0.0                 28.8
...          ...         ...                ...                  ...
18301  Quang Nam  2026-07-18                2.8                 33.6
18302  Quang Nam  2026-07-19                0.4                 33.9
18303  Quang Nam  2026-07-20                2.1                 32.8
18304  Quang Nam  2026-07-21                0.1                 33.4
18305  Quang Nam  2026-07-22                2.3                 32.3

       relative_humidity_2m_mean  surface_pressure_mean  wind_speed_10m_max  \
0                             68                 1000.4                24.8
1                             70                  998.7                20.9
2                             79                  999.6                 6.9
3                             85                  999.9                11.5
4                             74                  997.5                25.2
...                          ...                    ...                 ...
18301                         50                 1004.0                15.1
18302                         47                 1004.2                10.7
18303                         52                 1004.7                19.9
18304                         49                 1005.4                13.0
18305                         55                 1005.6                20.6

       river_discharge
0                 0.53
1                 0.44
2                 0.42
3                 0.44
4                 0.41
...                ...
18301             6.85
18302             6.64
18303             6.53
18304             6.41
18305             6.18

[18306 rows x 8 columns]>

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18306 entries, 0 to 18305
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Location                   18306 non-null  object
 1   time                       18306 non-null  object
 2   precipitation_sum          18306 non-null  float64
 3   temperature_2m_mean        18306 non-null  float64
 4   relative_humidity_2m_mean  18306 non-null  int64
 5   surface_pressure_mean      18306 non-null  float64
 6   wind_speed_10m_max         18306 non-null  float64
 7   river_discharge            18306 non-null  float64
dtypes: float64(5), int64(1), object(2)
memory usage: 1.1+ MB

In [13]:
df.describe()

,precipitation_sum,temperature_2m_mean,relative_humidity_2m_mean,surface_pressure_mean,wind_speed_10m_max,river_discharge
count,18306.000000,18306.000000,18306.000000,18306.000000,18306.00000,18306.000000
mean,7.869933,25.765317,82.986398,1009.338763,14.34056,23.565921
std,16.864720,3.290227,7.112917,5.201800,4.61238,68.753596
min,0.000000,14.100000,45.000000,984.400000,4.20000,0.080000
25%,0.200000,23.300000,79.000000,1005.200000,11.30000,0.660000
50%,2.150000,26.000000,84.000000,1008.900000,13.60000,6.530000
75%,8.400000,28.400000,88.000000,1013.300000,16.60000,14.802500
max,398.800000,34.600000,97.000000,1028.400000,64.60000,1569.360000

In [14]:
df = df.rename(columns = {
    "Location": "location",
    "time": "date",
    "precipitation_sum": "rainfall",
    "temperature_2m_mean": "temperature",
    "relative_humidity_2m_mean": "humidity",
    "surface_pressure_mean": "pressure",
    "wind_speed_10m_max": "wind_speed"
})

In [15]:
df["date"] = pd.to_datetime(df["date"])
df['humidity'] = df['humidity'].astype('float64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18306 entries, 0 to 18305
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   location         18306 non-null  object
 1   date             18306 non-null  datetime64[ns]
 2   rainfall         18306 non-null  float64
 3   temperature      18306 non-null  float64
 4   humidity         18306 non-null  float64
 5   pressure         18306 non-null  float64
 6   wind_speed       18306 non-null  float64
 7   river_discharge  18306 non-null  float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 1.1+ MB

In [16]:
df.head()

,location,date,rainfall,temperature,humidity,pressure,wind_speed,river_discharge
0,Hue,2001-07-01,0.0,28.6,68.0,1000.4,24.8,0.53
1,Hue,2001-07-02,0.2,29.1,70.0,998.7,20.9,0.44
2,Hue,2001-07-03,1.8,28.6,79.0,999.6,6.9,0.42
3,Hue,2001-07-04,13.8,27.8,85.0,999.9,11.5,0.44
4,Hue,2001-07-05,0.0,28.8,74.0,997.5,25.2,0.41

In [17]:
cols = ["date","location"]
other_cols = [c for c in df.columns if c not in cols]
df = df[cols + other_cols]
df.head()

,date,location,rainfall,temperature,humidity,pressure,wind_speed,river_discharge
0,2001-07-01,Hue,0.0,28.6,68.0,1000.4,24.8,0.53
1,2001-07-02,Hue,0.2,29.1,70.0,998.7,20.9,0.44
2,2001-07-03,Hue,1.8,28.6,79.0,999.6,6.9,0.42
3,2001-07-04,Hue,13.8,27.8,85.0,999.9,11.5,0.44
4,2001-07-05,Hue,0.0,28.8,74.0,997.5,25.2,0.41

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18306 entries, 0 to 18305
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             18306 non-null  datetime64[ns]
 1   location         18306 non-null  object
 2   rainfall         18306 non-null  float64
 3   temperature      18306 non-null  float64
 4   humidity         18306 non-null  float64
 5   pressure         18306 non-null  float64
 6   wind_speed       18306 non-null  float64
 7   river_discharge  18306 non-null  float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 1.1+ MB

In [20]:
df.describe()

,date,rainfall,temperature,humidity,pressure,wind_speed,river_discharge
count,18306,18306.000000,18306.000000,18306.000000,18306.000000,18306.00000,18306.000000
mean,2014-01-10 00:00:00,7.869933,25.765317,82.986398,1009.338763,14.34056,23.565921
min,2001-07-01 00:00:00,0.000000,14.100000,45.000000,984.400000,4.20000,0.080000
25%,2007-10-06 00:00:00,0.200000,23.300000,79.000000,1005.200000,11.30000,0.660000
50%,2014-01-10 00:00:00,2.150000,26.000000,84.000000,1008.900000,13.60000,6.530000
75%,2020-04-16 00:00:00,8.400000,28.400000,88.000000,1013.300000,16.60000,14.802500
max,2026-07-22 00:00:00,398.800000,34.600000,97.000000,1028.400000,64.60000,1569.360000
std,NaN,16.864720,3.290227,7.112917,5.201800,4.61238,68.753596

In [21]:
import os

In [22]:
output_path = '../data/cleaned/weather_cleaned.csv'

# Export CSV
df.to_csv(output_path, index=False)

print('Done')

Done