In [21]:
import pandas as pd
import numpy as np

In [22]:
label = pd.read_csv("../data/label_raw/label_raw.csv")

label.head()

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,...,"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,GADM Admin Units,Entry Date,Last Update
0,2025-0303-ECU,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,NaN,NaN,ECU,...,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,2025-04-28,2026-05-15
1,2026-0153-KEN,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,KEN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-09,2026-05-15
2,2025-0750-AFG,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,GLIDE:EQ-2025-000153,NaN,AFG,...,NaN,NaN,NaN,180000.0,180000.0,100.0,NaN,NaN,2025-09-01,2026-05-15
3,2026-0305-AFG,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,AFG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-05-04,2026-05-11
4,2024-0962-AGO,No,nat-bio-epi-bac,Natural,Biological,Epidemic,Bacterial disease,GLIDE:EP-2025-000013,Cholera,AGO,...,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,2025-01-17,2026-05-15

In [23]:
label.columns

Index(['DisNo.', 'Historic', 'Classification Key', 'Disaster Group',
       'Disaster Subgroup', 'Disaster Type', 'Disaster Subtype',
       'External IDs', 'Event Name', 'ISO', 'Country', 'Subregion', 'Region',
       'Location', 'Origin', 'Associated Types', 'OFDA/BHA Response', 'Appeal',
       'Declaration', 'AID Contribution ('000 US$)', 'Magnitude',
       'Magnitude Scale', 'Latitude', 'Longitude', 'River Basin', 'Start Year',
       'Start Month', 'Start Day', 'End Year', 'End Month', 'End Day',
       'Total Deaths', 'No. Injured', 'No. Affected', 'No. Homeless',
       'Total Affected', 'Reconstruction Costs ('000 US$)',
       'Reconstruction Costs, Adjusted ('000 US$)',
       'Insured Damage ('000 US$)', 'Insured Damage, Adjusted ('000 US$)',
       'Total Damage ('000 US$)', 'Total Damage, Adjusted ('000 US$)', 'CPI',
       'Admin Units', 'GADM Admin Units', 'Entry Date', 'Last Update'],
      dtype='object')

In [24]:
label = label[
    [
        "Location",
        'Start Year',
        'Start Month',
        'Start Day',
        'End Year', 
        'End Month',
        'End Day',
    ]
]

label.head()

,Location,Start Year,Start Month,Start Day,End Year,End Month,End Day
0,"Esmeraldas, Eloy Alfaro, Atacames, Muisne, Qui...",2025,4.0,25.0,2025,4.0,25.0
1,"Mombasa, Kwale, Kilifi, Tana River, Lamu, Tait...",2026,3.0,6.0,2026,3.0,31.0
2,"Chawka, Nurgal, chapa Dara, Dara-e-Pech and Wa...",2025,8.0,31.0,2025,8.0,31.0
3,"Kabul, Bamiyan, Paktia, Ghor, Badghis, Balkh, ...",2026,4.0,24.0,2026,5.0,1.0
4,Cacuaco (Luanda province); Bengo; Icolo e Beng...,2025,1.0,7.0,2025,10.0,NaN

In [25]:
label.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17698 entries, 0 to 17697
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Location     16901 non-null  object
 1   Start Year   17698 non-null  int64
 2   Start Month  17624 non-null  float64
 3   Start Day    16106 non-null  float64
 4   End Year     17698 non-null  int64
 5   End Month    17527 non-null  float64
 6   End Day      16191 non-null  float64
dtypes: float64(4), int64(2), object(1)
memory usage: 968.0+ KB

In [26]:
label.describe()

,Start Year,Start Month,Start Day,End Year,End Month,End Day
count,17698.000000,17624.000000,16106.000000,17698.000000,17527.000000,16191.000000
mean,2011.726749,6.559578,15.396747,2011.755227,6.684544,15.911926
std,7.735968,3.438019,8.974747,7.740040,3.417444,8.915423
min,2000.000000,1.000000,1.000000,1988.000000,1.000000,1.000000
25%,2005.000000,4.000000,8.000000,2005.000000,4.000000,8.000000
50%,2011.000000,7.000000,15.000000,2011.000000,7.000000,16.000000
75%,2019.000000,9.000000,23.000000,2019.000000,10.000000,24.000000
max,2026.000000,12.000000,31.000000,2026.000000,12.000000,31.000000

In [27]:
label = label[
    label["Location"].str.contains(
        "Thua Thien Hue|Quang Nam",
        case = False,
        na=False
    )
].copy()
label.head()

,Location,Start Year,Start Month,Start Day,End Year,End Month,End Day
353,"Quang Nam, Bình Dinh, Khánh Hòa, Phú Yên",2020,11.0,10.0,2020,11.0,10.0
1238,"Da Nang, Quang Nam (Duy Xuyen, Nong Son distri...",2015,9.0,14.0,2015,9.0,14.0
1882,"Quang Ngai, Binh Dinh, Quang Nam, Da Nang City...",2013,11.0,14.0,2013,11.0,20.0
1890,"Da Nang City, Quang Nam, Thua Thien - Hue, Qua...",2013,10.0,10.0,2013,10.0,15.0
2840,"Quang Ngai, Quang Nam, Binh Dinh, Quang Tri, P...",2003,10.0,15.0,2003,10.0,22.0

In [28]:
label["Start Day"] = (
    label["Start Day"]
    .fillna(1)
    .astype(int)
)

label["End Day"] = (
    label["End Day"]
    .fillna(1)
    .astype(int)
)

In [29]:
label["start_date"] = pd.to_datetime(
    dict(
        year=label["Start Year"],
        month=label["Start Month"],
        day=label["Start Day"]
    )
)

In [30]:
label["end_date"] = pd.to_datetime(
    dict(
        year=label["End Year"],
        month=label["End Month"],
        day=label["End Day"]
    )
)

In [31]:
label.head()

,Location,Start Year,Start Month,Start Day,End Year,End Month,End Day,start_date,end_date
353,"Quang Nam, Bình Dinh, Khánh Hòa, Phú Yên",2020,11.0,10,2020,11.0,10,2020-11-10,2020-11-10
1238,"Da Nang, Quang Nam (Duy Xuyen, Nong Son distri...",2015,9.0,14,2015,9.0,14,2015-09-14,2015-09-14
1882,"Quang Ngai, Binh Dinh, Quang Nam, Da Nang City...",2013,11.0,14,2013,11.0,20,2013-11-14,2013-11-20
1890,"Da Nang City, Quang Nam, Thua Thien - Hue, Qua...",2013,10.0,10,2013,10.0,15,2013-10-10,2013-10-15
2840,"Quang Ngai, Quang Nam, Binh Dinh, Quang Tri, P...",2003,10.0,15,2003,10.0,22,2003-10-15,2003-10-22

In [32]:
rows = []

for _, row in label.iterrows():
    locations = str(row["Location"]).split(",")
    for location in locations:
        rows.append({
            "location": location.strip(),
            "start_date": row["start_date"],
            "end_date": row["end_date"]
        })

label = pd.DataFrame(rows)

label.head()

    location start_date   end_date
0  Quang Nam 2020-11-10 2020-11-10
1  Bình Dinh 2020-11-10 2020-11-10
2  Khánh Hòa 2020-11-10 2020-11-10
3    Phú Yên 2020-11-10 2020-11-10
4    Da Nang 2015-09-14 2015-09-14

In [33]:
label = label[
    label["location"].isin(
        [
            "Thua Thien Hue",
            "Quang Nam"
        ]
    )
]

label

            location start_date   end_date
0          Quang Nam 2020-11-10 2020-11-10
11         Quang Nam 2013-11-14 2013-11-20
17         Quang Nam 2013-10-10 2013-10-15
21         Quang Nam 2003-10-15 2003-10-22
28    Thua Thien Hue 2005-10-07 2005-10-10
...              ...        ...        ...
1347       Quang Nam 2025-12-03 2025-12-06
1348       Quang Nam 2025-12-10 2025-12-12
1349       Quang Nam 2025-12-15 2025-12-17
1350       Quang Nam 2025-12-22 2025-12-23
1351       Quang Nam 2025-12-26 2025-12-28

[882 rows x 3 columns]

In [34]:
rows = []
for _, row in label.iterrows():
    dates = pd.date_range(
        row["start_date"],
        row["end_date"]
    )
    for d in dates:
        rows.append({
            "date": d,
            "location": row["location"],
            "flood": 1
        })

label_daily = pd.DataFrame(rows)

label_daily.head()

        date   location  flood
0 2020-11-10  Quang Nam      1
1 2013-11-14  Quang Nam      1
2 2013-11-15  Quang Nam      1
3 2013-11-16  Quang Nam      1
4 2013-11-17  Quang Nam      1

In [35]:
label_daily["location"] = label_daily["location"].replace(
    "Thua Thien Hue",
    "Hue"
)

In [36]:
label_daily.duplicated().sum()

np.int64(291)

In [37]:
label_daily = label_daily.drop_duplicates(
    subset=[
        "date",
        "location"
    ]
)

label_daily = label_daily.sort_values(
    [
        "location",
        "date"
    ]
)

label_daily.head()

          date location  flood
714 2001-08-04      Hue      1
715 2001-08-05      Hue      1
716 2001-08-06      Hue      1
717 2001-08-10      Hue      1
718 2001-08-11      Hue      1

In [38]:
label_daily["location_id"] = label_daily["location"].map({
    "Hue":1,
    "Quang Nam":2
}).astype("Int64")

label_daily.head()

          date location  flood  location_id
714 2001-08-04      Hue      1            1
715 2001-08-05      Hue      1            1
716 2001-08-06      Hue      1            1
717 2001-08-10      Hue      1            1
718 2001-08-11      Hue      1            1

In [39]:
label_daily = label_daily.drop(columns = ['location'])
label_daily.head()

          date  flood  location_id
714 2001-08-04      1            1
715 2001-08-05      1            1
716 2001-08-06      1            1
717 2001-08-10      1            1
718 2001-08-11      1            1

In [40]:
label_daily.to_csv("../data/cleaned/label_cleaned.csv",index=False)