In [167]:
import pandas as pd

In [168]:
label = pd.read_csv("../data/train/label_raw.csv")

label.head

<bound method NDFrame.head of               DisNo. Historic Classification Key Disaster Group  \
0      2025-0303-ECU       No    nat-geo-ear-gro        Natural
1      2026-0153-KEN       No    nat-hyd-flo-flo        Natural
2      2025-0750-AFG       No    nat-geo-ear-gro        Natural
3      2026-0305-AFG       No    nat-hyd-flo-flo        Natural
4      2024-0962-AGO       No    nat-bio-epi-bac        Natural
...              ...      ...                ...            ...
15984  2019-0563-MAR       No    tec-tra-wat-wat  Technological
15985  2019-0566-IRN       No    tec-tra-roa-roa  Technological
15986  2019-0567-SVK       No    tec-tra-roa-roa  Technological
15987  2019-0576-FRA       No    nat-hyd-flo-flo        Natural
15988  2019-0579-DJI       No    nat-hyd-flo-fla        Natural

      Disaster Subgroup Disaster Type   Disaster Subtype  \
0           Geophysical    Earthquake    Ground movement
1          Hydrological         Flood    Flood (General)
2           Geophysical    Earthquake    Ground movement
3          Hydrological         Flood    Flood (General)
4            Biological      Epidemic  Bacterial disease
...                 ...           ...                ...
15984         Transport         Water              Water
15985         Transport          Road               Road
15986         Transport          Road               Road
15987      Hydrological         Flood    Flood (General)
15988      Hydrological         Flood        Flash flood

               External IDs    Event Name  ISO  ...  \
0                       NaN           NaN  ECU  ...
1                       NaN           NaN  KEN  ...
2      GLIDE:EQ-2025-000153           NaN  AFG  ...
3                       NaN           NaN  AFG  ...
4      GLIDE:EP-2025-000013       Cholera  AGO  ...
...                     ...           ...  ...  ...
15984                   NaN  Fishing boat  MAR  ...
15985                   NaN           NaN  IRN  ...
15986                   NaN           NaN  SVK  ...
15987            HANZE:2112           NaN  FRA  ...
15988  GLIDE:FF-2019-000161           NaN  DJI  ...

      Reconstruction Costs, Adjusted ('000 US$) Insured Damage ('000 US$)  \
0                                           NaN                       NaN
1                                           NaN                       NaN
2                                           NaN                       NaN
3                                           NaN                       NaN
4                                           NaN                       NaN
...                                         ...                       ...
15984                                       NaN                       NaN
15985                                       NaN                       NaN
15986                                       NaN                       NaN
15987                                       NaN                       NaN
15988                                       NaN                       NaN

      Insured Damage, Adjusted ('000 US$) Total Damage ('000 US$)  \
0                                     NaN                     NaN
1                                     NaN                     NaN
2                                     NaN                180000.0
3                                     NaN                     NaN
4                                     NaN                     NaN
...                                   ...                     ...
15984                                 NaN                     NaN
15985                                 NaN                     NaN
15986                                 NaN                     NaN
15987                                 NaN                     NaN
15988                                 NaN                     NaN

      Total Damage, Adjusted ('000 US$)         CPI  \
0                                   NaN  100.000000
1                                   NaN         NaN
2                              180000.0  100.000000
3                                   NaN         NaN
4                                   NaN  100.000000
...                                 ...         ...
15984                               NaN   79.410785
15985                               NaN   79.410785
15986                               NaN   79.410785
15987                               NaN   79.410785
15988                               NaN   79.410785

                                             Admin Units  \
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                                    NaN
4                                                    NaN
...                                                  ...
15984                                                NaN
15985                                                NaN
15986                                                NaN
15987  [{"adm2_code":16321,"adm2_name":"Alpes-maritim...
15988  [{"adm1_code":1093,"adm1_name":"Ali Sabieh"},{...

                                        GADM Admin Units  Entry Date  \
0                                                    NaN  2025-04-28
1                                                    NaN  2026-03-09
2                                                    NaN  2025-09-01
3                                                    NaN  2026-05-04
4                                                    NaN  2025-01-17
...                                                  ...         ...
15984                                                NaN  2019-11-25
15985                                                NaN  2019-11-25
15986                                                NaN  2019-11-25
15987  [{"gid_2":"FRA.13.2_1","migration_date":"2025-...  2019-12-04
15988  [{"gid_1":"DJI.1_2","migration_date":"2025-12-...  2019-12-04

       Last Update
0       2026-05-15
1       2026-05-15
2       2026-05-15
3       2026-05-11
4       2026-05-15
...            ...
15984   2023-09-25
15985   2023-09-25
15986   2023-09-25
15987   2025-12-20
15988   2025-12-20

[15989 rows x 47 columns]>

In [169]:
label = label[
    label["Location"].str.contains(
        "Thua Thien Hue|Quang Nam",
        case = False,
        na=False
    )
].copy()
label.head()

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,...,"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,GADM Admin Units,Entry Date,Last Update
341,2020-0542-VNM,No,nat-met-sto-tro,Natural,Meteorological,Storm,Tropical cyclone,NaN,Tropical storm 'Etau' (Tonyo),VNM,...,NaN,NaN,NaN,5260.0,6543.0,80.390383,"[{""adm1_code"":3333,""adm1_name"":""Binh Dinh""},{""...","[{""gid_1"":""VNM.32_1"",""migration_date"":""2025-12...",2020-12-10,2025-12-20
1226,2015-0620-VNM,No,nat-met-sto-tro,Natural,Meteorological,Storm,Tropical cyclone,GLIDE:TC-2015-000188,Cyclone Vamco,VNM,...,NaN,NaN,NaN,218.0,296.0,73.620803,"[{""adm1_code"":3340,""adm1_name"":""Da Nang City""}...","[{""gid_1"":""VNM.19_1"",""migration_date"":""2025-12...",2018-05-24,2025-12-20
1870,2013-0443-VNM,No,nat-hyd-flo-riv,Natural,Hydrological,Flood,Riverine flood,GLIDE:FL-2013-000142,NaN,VNM,...,NaN,NaN,NaN,72000.0,99503.0,72.359737,"[{""adm1_code"":3333,""adm1_name"":""Binh Dinh""},{""...","[{""gid_1"":""VNM.19_1"",""migration_date"":""2025-12...",2014-03-20,2025-12-20
1878,2013-0430-VNM,No,nat-met-sto-tro,Natural,Meteorological,Storm,Tropical cyclone,GLIDE:TC-2013-000132,Tropical storm Nari (SAnti),VNM,...,NaN,NaN,NaN,76000.0,105031.0,72.359737,"[{""adm1_code"":3340,""adm1_name"":""Da Nang City""}...","[{""gid_1"":""VNM.19_1"",""migration_date"":""2025-12...",2013-11-26,2025-12-20
2791,2003-0505-VNM,No,nat-hyd-flo-coa,Natural,Hydrological,Flood,Coastal flood,NaN,NaN,VNM,...,NaN,NaN,NaN,32000.0,56003.0,57.140035,"[{""adm1_code"":3333,""adm1_name"":""Binh Dinh""},{""...","[{""gid_1"":""VNM.45_1"",""migration_date"":""2025-12...",2004-01-27,2025-12-20

In [170]:
label["Start Day"] = (
    label["Start Day"]
    .fillna(1)
    .astype(int)
)

label["End Day"] = (
    label["End Day"]
    .fillna(1)
    .astype(int)
)

In [171]:
label["start_date"] = pd.to_datetime(
    dict(
        year=label["Start Year"],
        month=label["Start Month"],
        day=label["Start Day"]
    )
)

In [172]:
label["end_date"] = pd.to_datetime(
    dict(
        year=label["End Year"],
        month=label["End Month"],
        day=label["End Day"]
    )
)

In [173]:
label = label[
    [
        "DisNo.",
        "Location",
        "Latitude",
        "Longitude",
        "start_date",
        "end_date"
    ]
]

label.head()

,DisNo.,Location,Latitude,Longitude,start_date,end_date
341,2020-0542-VNM,"Quang Nam, Bình Dinh, Khánh Hòa, Phú Yên",NaN,NaN,2020-11-10,2020-11-10
1226,2015-0620-VNM,"Da Nang, Quang Nam (Duy Xuyen, Nong Son distri...",NaN,NaN,2015-09-14,2015-09-14
1870,2013-0443-VNM,"Quang Ngai, Binh Dinh, Quang Nam, Da Nang City...",15.58,107.7,2013-11-14,2013-11-20
1878,2013-0430-VNM,"Da Nang City, Quang Nam, Thua Thien - Hue, Qua...",NaN,NaN,2013-10-10,2013-10-15
2791,2003-0505-VNM,"Quang Ngai, Quang Nam, Binh Dinh, Quang Tri, P...",NaN,NaN,2003-10-15,2003-10-22

In [174]:
rows = []

for _, row in label.iterrows():
    provinces = str(row["Location"]).split(",")
    for province in provinces:
        rows.append({
            "province": province.strip(),
            "start_date": row["start_date"],
            "end_date": row["end_date"]
        })

label = pd.DataFrame(rows)

label.head()

    province start_date   end_date
0  Quang Nam 2020-11-10 2020-11-10
1  Bình Dinh 2020-11-10 2020-11-10
2  Khánh Hòa 2020-11-10 2020-11-10
3    Phú Yên 2020-11-10 2020-11-10
4    Da Nang 2015-09-14 2015-09-14

In [175]:
label = label[
    label["province"].isin(
        [
            "Thua Thien Hue",
            "Quang Nam"
        ]
    )
]

label

           province start_date   end_date
0         Quang Nam 2020-11-10 2020-11-10
11        Quang Nam 2013-11-14 2013-11-20
17        Quang Nam 2013-10-10 2013-10-15
21        Quang Nam 2003-10-15 2003-10-22
28   Thua Thien Hue 2005-10-07 2005-10-10
35        Quang Nam 2005-12-04 2005-12-24
48   Thua Thien Hue 2006-08-12 2006-08-30
57        Quang Nam 2006-09-27 2006-10-06
62        Quang Nam 2007-11-10 2007-11-21
112       Quang Nam 2011-06-19 2011-06-24
116       Quang Nam 2001-10-20 2001-10-24
129       Quang Nam 2006-10-12 2006-10-17
196       Quang Nam 2009-09-28 2009-09-29
204       Quang Nam 2009-11-02 2009-11-02
214       Quang Nam 2013-09-30 2013-10-15
256       Quang Nam 2015-12-01 2017-02-01
274       Quang Nam 2017-11-19 2017-11-24
277       Quang Nam 2021-11-27 2021-11-30
283  Thua Thien Hue 2022-10-13 2022-10-15
287       Quang Nam 2024-10-25 2024-10-30
293       Quang Nam 2003-11-11 2003-11-14
297       Quang Nam 2005-11-02 2005-11-04
303       Quang Nam 2007-09-29 2007-10-12
314       Quang Nam 2008-10-19 2008-10-20
321       Quang Nam 2016-12-12 2016-12-20
331       Quang Nam 2017-11-04 2017-11-05
339       Quang Nam 2018-12-08 2018-12-10
346       Quang Nam 2020-10-29 2020-10-29
350       Quang Nam 2020-10-06 2020-11-03
355       Quang Nam 2020-10-06 2020-11-03
363       Quang Nam 2022-12-01 2022-12-04
378       Quang Nam 2022-09-28 2022-09-29
381  Thua Thien Hue 2022-10-10 2022-10-11
385       Quang Nam 2004-11-26 2004-11-26
399       Quang Nam 2005-09-27 2005-09-30
408       Quang Nam 2007-10-28 2007-11-09
417       Quang Nam 2009-09-25 2009-09-28
448       Quang Nam 2013-09-24 2013-09-24
480       Quang Nam 2013-09-03 2013-09-04
494       Quang Nam 2013-09-16 2013-09-18

In [176]:
rows = []
for _, row in label.iterrows():
    dates = pd.date_range(
        row["start_date"],
        row["end_date"]
    )
    for d in dates:
        rows.append({
            "date": d,
            "province": row["province"],
            "flood": 1
        })

label_daily = pd.DataFrame(rows)

label_daily.head()

        date   province  flood
0 2020-11-10  Quang Nam      1
1 2013-11-14  Quang Nam      1
2 2013-11-15  Quang Nam      1
3 2013-11-16  Quang Nam      1
4 2013-11-17  Quang Nam      1

In [177]:
label_daily = label_daily.drop_duplicates(
    subset=[
        "date",
        "province"
    ]
)

label_daily = label_daily.sort_values(
    [
        "province",
        "date"
    ]
)

label_daily.head()

         date   province  flood
94 2001-10-20  Quang Nam      1
95 2001-10-21  Quang Nam      1
96 2001-10-22  Quang Nam      1
97 2001-10-23  Quang Nam      1
98 2001-10-24  Quang Nam      1

In [178]:
df = pd.read_csv("../data/train/master_weather.csv")
df.head()

,location_id,location,date,rainfall,temperature,humidity,pressure,wind_speed,river_discharge,month,season,rainfall_3days,rainfall_7days,river_discharge_change
0,1,Hue,2001-01-01,2.6,20.200001,82.0,1013.299988,9.6,1.56,1,Dry,2.6,2.6,0.00
1,1,Hue,2001-01-02,0.0,21.100000,82.0,1011.799988,14.1,1.09,1,Dry,2.6,2.6,-0.47
2,1,Hue,2001-01-03,1.0,21.600000,85.0,1012.900024,12.7,0.75,1,Dry,3.6,3.6,-0.34
3,1,Hue,2001-01-04,6.7,21.200001,91.0,1014.200012,15.5,0.72,1,Dry,7.7,10.3,-0.03
4,1,Hue,2001-01-05,4.8,22.100000,90.0,1014.000000,14.5,0.92,1,Dry,12.5,15.1,0.20

In [179]:
df["date"] =pd.to_datetime(df["date"])

In [180]:
label_daily.rename(columns={"province":"location"},inplace = True)

label_daily.replace({
    "Thua Thien Hue":"Hue"
},inplace = True)

label_daily.head()

         date   location  flood
94 2001-10-20  Quang Nam      1
95 2001-10-21  Quang Nam      1
96 2001-10-22  Quang Nam      1
97 2001-10-23  Quang Nam      1
98 2001-10-24  Quang Nam      1

In [181]:
master_data = df.merge(
    label_daily[
        [
            "date",
            "location",
            "flood",
        ]
    ],
    on=["date","location"],
    how="left"
)

master_data.head()

,location_id,location,date,rainfall,temperature,humidity,pressure,wind_speed,river_discharge,month,season,rainfall_3days,rainfall_7days,river_discharge_change,flood
0,1,Hue,2001-01-01,2.6,20.200001,82.0,1013.299988,9.6,1.56,1,Dry,2.6,2.6,0.00,NaN
1,1,Hue,2001-01-02,0.0,21.100000,82.0,1011.799988,14.1,1.09,1,Dry,2.6,2.6,-0.47,NaN
2,1,Hue,2001-01-03,1.0,21.600000,85.0,1012.900024,12.7,0.75,1,Dry,3.6,3.6,-0.34,NaN
3,1,Hue,2001-01-04,6.7,21.200001,91.0,1014.200012,15.5,0.72,1,Dry,7.7,10.3,-0.03,NaN
4,1,Hue,2001-01-05,4.8,22.100000,90.0,1014.000000,14.5,0.92,1,Dry,12.5,15.1,0.20,NaN

In [182]:
master_data["flood"] = master_data["flood"].fillna(0)

master_data.head()

,location_id,location,date,rainfall,temperature,humidity,pressure,wind_speed,river_discharge,month,season,rainfall_3days,rainfall_7days,river_discharge_change,flood
0,1,Hue,2001-01-01,2.6,20.200001,82.0,1013.299988,9.6,1.56,1,Dry,2.6,2.6,0.00,0.0
1,1,Hue,2001-01-02,0.0,21.100000,82.0,1011.799988,14.1,1.09,1,Dry,2.6,2.6,-0.47,0.0
2,1,Hue,2001-01-03,1.0,21.600000,85.0,1012.900024,12.7,0.75,1,Dry,3.6,3.6,-0.34,0.0
3,1,Hue,2001-01-04,6.7,21.200001,91.0,1014.200012,15.5,0.72,1,Dry,7.7,10.3,-0.03,0.0
4,1,Hue,2001-01-05,4.8,22.100000,90.0,1014.000000,14.5,0.92,1,Dry,12.5,15.1,0.20,0.0

In [183]:
master_data.describe()

,location_id,date,rainfall,temperature,humidity,pressure,wind_speed,river_discharge,month,rainfall_3days,rainfall_7days,river_discharge_change,flood
count,18622.000000,18622,18622.000000,18622.000000,18622.000000,18622.000000,18622.000000,18622.000000,18622.000000,18622.000000,18622.000000,18622.000000,18622.000000
mean,1.500000,2013-09-30 00:00:00,7.840307,25.742439,83.083879,1009.344190,14.313602,23.388731,6.464504,23.517152,54.865890,-0.001690,0.035335
min,1.000000,2001-01-01 00:00:00,0.000000,14.100000,45.000000,984.400024,4.200000,0.080000,1.000000,0.000000,0.000000,-776.870056,0.000000
25%,1.000000,2007-05-17 06:00:00,0.200000,23.299999,80.000000,1005.299988,11.200000,0.670000,3.000000,2.300000,11.700000,-0.740000,0.000000
50%,1.500000,2013-09-30 00:00:00,2.100000,26.000000,84.000000,1009.000000,13.600000,6.530000,6.000000,9.900000,30.800001,-0.040000,0.000000
75%,2.000000,2020-02-13 18:00:00,8.400000,28.400000,88.000000,1013.299988,16.600000,14.890000,9.000000,27.875000,69.374999,0.197500,0.000000
max,2.000000,2026-06-29 00:00:00,398.799988,34.599998,97.000000,1028.400024,64.599998,1569.359985,12.000000,578.099998,692.799995,815.269958,1.000000
std,0.500013,NaN,16.772924,3.278230,7.024499,5.187067,4.598161,68.224638,3.448782,38.966788,71.217082,37.588660,0.184629

In [184]:
master_data.to_csv("../data/train/data_train.csv", index=False)